# Create subfolder within the current working directory

dir.create("Data")
dir.create("R")
dir.create("R/RTM")
dir.create("R/RTM/PCB1")
dir.create("R/RTM/PCB4")
dir.create("R/RTM/PCB6")
dir.create("R/RTM/PCB7")
dir.create("R/RTM/PCB9")
dir.create("R/RTM/PCB14")
dir.create("R/RTM/PCB16")
dir.create("R/RTM/PCB17")
dir.create("R/RTM/PCB18+30")
dir.create("R/RTM/PCB19")
dir.create("R/RTM/PCB25")
dir.create("R/RTM/PCB26+29")
dir.create("R/RTM/PCB27")
dir.create("R/RTM/PCB31")
dir.create("R/RTM/PCB32")
dir.create("R/RTM/PCB34")
dir.create("R/RTM/PCB44+47+65")
dir.create("R/RTM/PCB48")
dir.create("R/RTM/PCB50+53")
dir.create("R/RTM/PCB54")
dir.create("R/RTM/PCB59+62+75")
dir.create("R/RTM/PCB93+100")
dir.create("R/RTM/PCB94")
dir.create("R/RTM/PCB96")
dir.create("R/RTM/PCB103")
dir.create("R/RTM/PCB104")
dir.create("R/StatAnalysis")
dir.create("Output")
dir.create("Output/Data")
dir.create("Output/Data/RTM")
dir.create("Output/Data/Stat")
dir.create("Output/Plots")
dir.create("Output/Plots/RTM")
dir.create("Output/Plots/TimeSeries")
dir.create("Output/Plots/TimeSeries/SPME/")
dir.create("Output/Plots/TimeSeries/PUF")



